_BASE_: "../../../detectron2/configs/COCO-Keypoints/Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000